### ISSUE TITLE
Niet werkende link "Circuits, fasedraden en geleiders" 

### ISSUE THREAD

**Issue by coreice** [Hoogspanningsnet/Mainsite#1]
De link naar de St(r)oomcursus deel drie op de website werkt niet meer.

http://www.hoogspanningsnet.com/over-hoogspanningsmasten/en-alles-eromheen/circuits-fasedraden-en-geleiders/

**Comment by HansNien** [comment]
Die hele set pagina's is uit het jaar kruik, zie de brakke URL. Note to myself: herschrijven, net zoals dat is gedaan met de series over verrommeling, trafostations, isolators en borden.

Voor nu: FIXED.
