### ISSUE TITLE
Opmerkingen op beheerdershandleiding

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Mainsite#3]
Ik heb op de handleiding de volgende opmerkingen:

- [x] Vervang user door gebruiker, de term user is nieuw volgens mij, we noemen ze overal gebruikers.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739414/15239c48-3182-11e7-88d2-55d39f153baa.png)

- [x] Link naat netkaart bijbel invoegen.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739467/46fe6bda-3182-11e7-94aa-bfec3bd6c7b8.png)

- [x] Ik zou het handig vinden als beheerders ook toegang hebben tot de WA-groep Netkaart Ontwikkelaars.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739501/7063f4cc-3182-11e7-8a2b-98c67daa56f5.png)

- [x] "LoFi" vervangen door "basic qua layout", (niet iedereen kent de term LoFi)

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739539/95b26240-3182-11e7-9d16-e17dc2ba37fd.png)

- [x] De online informatie en foto's komen in een bepaalde zin wel mee:
De extra informatie kan bijv. vanuit GE worden weergegeven in de bekende balloons. In die zin wijkt deze download niet af van de normnale GE-kaart. In het download bestand worden URL opgenomen naar de balloons (met foto's).

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739607/e6505022-3182-11e7-944e-69722dd6048e.png)

- [x] Vermelden dat de download een KML bestand is, en dus alleen bruikbaar in GIS-tools als GE.

- [x] Vermelden hoe dit herkenbaar is in GE en webkaart:
GE: standaard pushpins bij iconen en witte verbindingen
Webkaart: Geen actie nodig

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739719/641814a4-3183-11e7-88cf-7aedd6fa5d0a.png)

- [x] Bovenstaande komt alleen voor bij het toevoegen van een nieuwe spanning die nog niet in de database voor komt. Evt even vermelden

- [x] Ik wil aan deze info nog wel wat meer toevoegen, maar dat komt dat tzt wel:
Aantal views, een paar grafieken, een link naar de heatmap etc

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739800/c20b9f22-3183-11e7-88d6-73683b30d48d.png)

- [x] Ik vindt dit een vage en onduidelijke term, graag vervanger door de normale term (beheerders)

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739852/03b2afd8-3184-11e7-938e-b6bcb47c966e.png)

- [x] Er wordt alleen het gebruik van GE-ondersteund, sommige GIS-tools vermoorden de KML-structuur waar ik afhankelijk van ben met importeren, hetgeen kan resulteren in een omgelegde database. Dus alleen GE gebruiken, dit ook voorschrijven.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25739886/294852f2-3184-11e7-9d81-c53d479352cd.png)

- [x] Ergens vermelden dat je uitgaat van de NL-versie van Google Earth en dat termen als "Tijdelijke plaatsen" en "Nieuw Pad" een andere naam kunnen hebben in een andere taal-versie.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740064/2fd47f00-3185-11e7-8d9b-84e0545daf32.png)

- [x] Een link naar de bijbel maken, bij voorkeur naar het juiste hoofdstuk

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740089/55e626bc-3185-11e7-9b8a-1a0fc1837a96.png)

- [x] Pictogram wijzigen in stationsicoon, of vermelden dat we hier statioonsicoon als voorbeeld nemen, maar dat de andere iconen op dezelfde manier werken.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740192/bff4716c-3185-11e7-8158-3d813e62bc53.png)

- [x] Ik plaats zelf het stationsicoon ergens (midden) in de polygoon met de hoogste spanning. Waarom? Goeie vraag.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740220/fb2e44e2-3185-11e7-9e57-c62dd8cd202f.png)

- [x] De naamgeving van bestanden is vrij te kiezen. Je kan iedere geldige bestandsnaam kiezen (zolang je maar in KML op slaat). Ikzelf gebruik meestal iets wat de essentie weergeeft van de import en de datum, in dit geval iets van "DE - Station Bassum 05-05-2017". Verder is het belangrijk dat je de rootmap van een land opslaat (die mapnaam in GE moet wel exact de juiste naam hebben).
Overigens bewaar ik al mn imports in een aparte map als een soort backup.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740349/6b66b2bc-3186-11e7-8001-c64e28f5bf66.png)

- [x] Zelfs geografische wijzigingen of een andere plaats in de boomstructuur (bijv door een andere spanning) aan de bestaande objecten worden herkend en verwerkt in de database (zie hoofdstuk ... wijzigen van bestaande info). 

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740436/e3a4032e-3186-11e7-96dd-3fdaa06956b0.png)

- [x] Advies is om een unieke filenaam per import te kiezen (zie ook voorgaand punt mbt filenaam)
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740481/016dae82-3187-11e7-966f-f3b0aa8f5239.png)
Zoals je kunt zien gebruikt knarvel wel een unieke filenaam:

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740579/6dcc8d0a-3187-11e7-9991-e1331dc28a59.png)

- [x] Paragraaf nummer invoegen en een link maken.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740656/b7018ce6-3187-11e7-9566-d2724c44adfb.png)

- [x] Het is idd geen pesterij, maar de reden is dat de mapnamen gebruikt worden om velden in de database te vullen, voor de formattering daarvan hebben we in de bijbel naamgevingsconventies opgenomen zodat er geen wildgroei ontstaat, dat willen we absoluut voorkomen (zie bijvoorbeeld naamgeving van lijnen in OSM). Het importscript steund op de juiste boomstructuur voor het vinden en verwerken van objecten op de netkaart in de database. Als je bij een import items bent kwijt geraakt stonden deze waarschijnlijk niet op de juiste plek in de boom of was de mapnaam verkeerd.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740860/9dd29642-3188-11e7-96e9-560a3056890e.png)

- [x] Ja kan natuurlijk ook, de verbinding in een bestaande map tekenen (bijv 50kV onder Liander) dan importeren en via de editorrechten de juiste spanning aan het nieuwe object toekennen (wellicht sneller, maar levert wel het juiste resultaat op, hoewel misschien niet de gewenste weg)

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25740978/1adaa792-3189-11e7-8f42-348d61151ddd.png)

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741012/34330f4a-3189-11e7-8d17-86fcd9803db7.png)
Zie voorgaande opmerking :)

- [x] Onjuist, je kan gewoon een nieuwe map aanmaken mits deze maar de naam "Netkaart <2-letter afkorting>" heeft en verder intern zo opgebouwd is als de andere landen. Zelf neem ik een copie van een land wat buiten beeld is en pas de land afko aan. Dit levert een boom die op de bovenste niveaus iig juiste mapnamen heeft.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741148/c6596496-3189-11e7-9be3-886d96a4975c.png)

- [x] Is dit de juiste term? Zoals ook op andere plekken gebruikt?

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741219/021f4de2-318a-11e7-9612-aa5ab467ba8e.png)

- [x] Benadrukken dat we dan niet boos zijn (dus inquisitie is niet de juiste term), MAAR WEL HEEL TELEURGESTELD. Er wordt regelmatig (meerdere malen per dag) een backup van de database gemaakt, die kan in een heel ernstig geval worden terug gezet, of we kunnen correcties via de database doen.

- [x] gaten in de database zijn niet erg, tekst verwijderen. Soms moet je veel objecten met de hand wissen via de omslachtige procedure (zie voorgaande paragraaf), maar dat is je terechte straf :)

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741397/eecd0a3a-318a-11e7-81f2-8e8f50d80e38.png)

- [x] Styling

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741415/0a1b6aca-318b-11e7-9355-f388651cd751.png)

- [x] Of neem bij erg grote aantallen (tientallen) contact op met de inquisitie, wellicht kunnen we iets via queries in de database doen.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741474/45db9904-318b-11e7-9530-85620d5a8d67.png)

- [x] Je kan ook een van de de volgende links gebruiken:
https://netkaart.hoogspanningsnet.com/edititem.php?ID=<ID invullen, als je dat weet>
of 
https://webkaart.hoogspanningsnet.com/edititem3.php?ID=<ID invullen, als je dat weet>

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741639/dd758518-318b-11e7-97a0-0ad6aab71a77.png)

- [x] Dit is een fout in een editor-actie, verplaatsen naar die handleiding.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/25741682/286df05a-318c-11e7-9173-793f9f28f6c2.png)
hetzelfde geldt voor VVS3

**Comment by HansNien** [comment]
Dank, dank, dank! Wat een pakket. Ik heb ze inmiddels allemaal doorgewerkt, verwerkt of aangepast en als het goed is ziet de tekst er nu stukken beter uit.

> Ja kan natuurlijk ook, de verbinding in een bestaande map tekenen (bijv 50kV onder Liander) dan importeren en via de editorrechten de juiste spanning aan het nieuwe object toekennen (wellicht sneller, maar levert wel het juiste resultaat op, hoewel misschien niet de gewenste weg)

Alleen deze heb ik er maar niet in gestopt. Als de cartograaf na import simpelweg vergeet dat hij deze handeling (bij deze methode) apart per object nog eens moet toepassen, dan hebben we straks verbindingen in het verkeerde netvlak, of verbindingen in hetzelfde netvlak waarbij dan altijd weer bij eentje wel een keer de concessiehouder of een andere eigenschap toch net weer is vergeten. Laat deze cheat maar mooi als een hidden trick voor wie hem toevallig kennen. In de meeste andere gevallen is handmatig de mappen aanmaken beter voor het overzicht. (Mijn twee centen.)
