### ISSUE TITLE
FAQ_ Vervang commerciele toepassing door Professionele toepassing

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Mainsite#8]
BaDu: 
We gebruiken de term commerciele toepassing, dat is wat beperkter.
TenneT bijvoorbeeld is geen commerciele toepassing.
Wellicht is de term Professionele toepassing beter?

Hans:
Hmm. Het woord commercieel was ooit opzettelijk gekozen om juist andere professionele toepassingen nog wel mogelijk te houden, waarbij vooral kon worden gedacht aan educatief of non-profit op eigen risico. Maar dat wordt sinds de verbeterde voorwaarden ook al expliciet genoemd (onderwijs en via de term kritiek gebruik). Dus eigenlijk heb je gelijk. Github 'm maar, morgen kan ik het wel aanpassen.

**Comment by HansNien** [comment]
Aangepast in de portalpagina, in de disclaimer, in de gebruiksvoorwaarden en in de handleiding. Op de meeste plekken is het woord commercieel vervangen door professioneel, en op plekken waar meer nuance nodig is worden ze beide genoemd. Nu de netkaartbijbel er nog op aanpassen.

**Comment by HansNien** [comment]
FIXED.
